### ISSUE TITLE
TypeError: : Cannot read property 'machine_identifier' of undefined

### ISSUE THREAD

**Issue by ColdIce1** [Transmogrify-for-Plex/Transmogrify-for-Plex-chrome#25]
So here is a bug report on 1.4.0
Chrome: Version 45.0.2454.101 m

```
utils.js:15 Transmogrify for Plex log: Server addresses fetched
utils.js:15 Transmogrify for Plex log: set active server as undefined
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'machine_identifier' of undefined
    at switchToServer (chrome-extension://jdogfefgaagaledbkgeffgbjlaaplpgo/stats.js:1045:27)
    at chrome-extension://jdogfefgaagaledbkgeffgbjlaaplpgo/stats.js:1185:9
    at chrome-extension://jdogfefgaagaledbkgeffgbjlaaplpgo/stats.js:81:9
    at chrome-extension://jdogfefgaagaledbkgeffgbjlaaplpgo/utils.js:83:13handler @ extensions::uncaught_exception_handler:8
```

**Comment by ColdIce1** [comment]
@Moussa You seen this issue yet?

**Comment by Moussa** [comment]
@ColdIce1 Unfortunately I'm no longer working on this extension, and bug fixes and such are left to other contributors if they wish to take over. I'll make this clear in the README.

**Comment by pdille** [comment]
I'll take a look. Can you provide more information in regards to this? First off, is it still a problem? And second, what exactly were you doing at the time of the error?
